/**
 * Sistema de Iconos SVG para WebCode
 * Integración con SVGRepo para reemplazar emoticones por SVGs escalables
 *
 * Mantiene coherencia con el sistema de diseño:
 * - Colores: Rosa #ff6680, Naranja #ff8f66, Púrpura #9333ea
 * - Estilo: Bold, geométrico, moderno
 */

export interface SvgIconProps {
  className?: string;
  size?: "sm" | "md" | "lg" | "xl";
  variant?: "default" | "primary" | "secondary" | "accent";
}

// Mapeo completo de emoticones a SVGs de SVGRepo
// Sistema expandido para migración completa de WebCode
export const EMOJI_TO_SVG_MAP = {
  // Documentación y feedback
  "✅": "check-circle",
  "❌": "x-circle",
  "⚠️": "alert-triangle",
  "🎯": "target",
  "📊": "bar-chart-3",
  "🎨": "palette",
  "💡": "lightbulb",
  "📝": "file-text",
  "🔧": "settings",
  "📋": "clipboard-list",
  "📚": "book-open",
  "⚡": "zap",
  "📱": "smartphone",
  "🎉": "party-popper",
  "🚀": "rocket",
  "💻": "laptop",
  "🌐": "globe",
  "📈": "trending-up",
  "⭐": "star",
  "🎁": "gift",
  "💎": "gem",
  "🔥": "flame",
  "🌟": "sparkles",
  "💫": "zap",
  "✨": "sparkles",

  // Comunicación y canales
  "📞": "phone",
  "📧": "mail",
  "💬": "message-circle",
  "🖥️": "monitor",
  "📹": "video",

  // Proceso y fases
  "🔍": "search",
  "🛡️": "shield",

  // Documentación y prompts (nuevos)
  "🧠": "brain",
  "📸": "camera",
  "⏰": "clock",
  "🔗": "link",
  "💭": "message-square",
  "🎪": "zap",
  "🎭": "palette",
  "🎬": "video",
  "🎵": "music",
  "🎶": "music",
  "🎸": "music",
  "🎹": "music",
  "🎺": "music",
  "🎻": "music",
  "🎲": "dice-6",
  "🎳": "bowling-ball",
  "🎮": "gamepad-2",
  "🎰": "slots",
  "🎱": "dice-6",
  "📐": "ruler",
  "📏": "ruler",
  "📌": "pin",
  "📍": "map-pin",
  "📎": "paperclip",
  "🖇️": "paperclip",
  "📖": "book-open",
  "📗": "book-open",
  "📘": "book-open",
  "📙": "book-open",
  "📕": "book-open",
  "📓": "book-open",
  "📔": "book-open",
  "📒": "book-open",
  "📑": "book-open",
  "🔖": "bookmark",
  "🏷️": "tag",
  "💰": "dollar-sign",
  "💸": "credit-card",
  "💳": "credit-card",
  "💴": "dollar-sign",
  "💵": "dollar-sign",
  "💶": "euro",
  "💷": "pound-sterling",
  "💹": "trending-up",
  "💺": "chair",
  "💼": "briefcase",
  "💽": "disc",
  "💾": "save",
  "💿": "disc",
  "📀": "disc",
  "📁": "folder",
  "📂": "folder-open",
  "📃": "file",
  "📄": "file",
  "📅": "calendar",
  "📆": "calendar",
  "📇": "card-index",
  "📉": "trending-down",
  "📛": "badge",
  "📜": "scroll",
  "📟": "radio",
  "📠": "fax",
  "📡": "satellite",
  "📢": "megaphone",
  "📣": "megaphone",
  "📤": "upload",
  "📥": "download",
  "📦": "package",
  "📨": "mail",
  "📩": "mail",
  "📪": "mailbox",
  "📫": "mailbox",
  "📬": "mailbox",
  "📭": "mailbox",
  "📮": "mailbox",
  "📯": "trumpet",
  "📰": "newspaper",
  "📲": "smartphone",
  "📳": "smartphone",
  "📴": "smartphone",
  "📵": "smartphone",
  "📶": "signal",
  "📷": "camera",
  "📺": "tv",
  "📻": "radio",
  "📼": "video",
  "📽️": "film",
  "📾": "disc",
  "📿": "prayer-beads",
  "🔀": "shuffle",
  "🔁": "repeat",
  "🔂": "repeat-1",
  "🔃": "rotate-cw",
  "🔄": "rotate-cw",
  "🔅": "sun",
  "🔆": "sun",
  "🔇": "volume-x",
  "🔈": "volume-1",
  "🔉": "volume-2",
  "🔊": "volume-2",
  "🔋": "battery",
  "🔌": "plug",
  "🔎": "search",
  "🔏": "lock",
  "🔐": "lock",
  "🔑": "key",
  "🔒": "lock",
  "🔓": "unlock",
  "🔔": "bell",
  "🔕": "bell-off",
  "🔙": "arrow-left",
  "🔚": "arrow-left",
  "🔛": "toggle-left",
  "🔜": "arrow-right",
  "🔝": "arrow-up",
  "🔞": "shield",
  "🔟": "hash",
  "🔠": "type",
  "🔡": "type",
  "🔢": "hash",
  "🔣": "hash",
  "🔤": "type",
  "🔦": "flashlight",
  "🔨": "hammer",
  "🔩": "nut",
  "🔪": "knife",
  "🔫": "gun",
  "🔬": "microscope",
  "🔭": "telescope",
  "🔮": "crystal-ball",
  "🔯": "star",
  "🔰": "shield",
  "🔱": "trident",
  "🔲": "square",
  "🔳": "square",
  "🔴": "circle",
  "🔵": "circle",
  "🔶": "triangle",
  "🔷": "triangle",
  "🔸": "triangle",
  "🔹": "triangle",
  "🔺": "triangle",
  "🔻": "triangle",
  "🔼": "triangle",
  "🔽": "triangle",
  "🕐": "clock",
  "🕑": "clock",
  "🕒": "clock",
  "🕓": "clock",
  "🕔": "clock",
  "🕕": "clock",
  "🕖": "clock",
  "🕗": "clock",
  "🕘": "clock",
  "🕙": "clock",
  "🕚": "clock",
  "🕛": "clock",
  "🕜": "clock",
  "🕝": "clock",
  "🕞": "clock",
  "🕟": "clock",
  "🕠": "clock",
  "🕡": "clock",
  "🕢": "clock",
  "🕣": "clock",
  "🕤": "clock",
  "🕥": "clock",
  "🕦": "clock",
  "🕧": "clock",
  "🕰️": "clock",
  "🕳️": "circle",
  "🕴️": "user",
  "🕵️": "user",
  "🕶️": "eye",
  "🕷️": "bug",
  "🕸️": "web",
  "🕹️": "gamepad-2",
  "🕺": "user",
  "🖊️": "pen",
  "🖋️": "pen",
  "🖌️": "paintbrush",
  "🖍️": "paintbrush",
  "🖎": "scissors",
  "🖏": "hand",
  "🖐️": "hand",
  "🖑": "hand",
  "🖒": "thumbs-up",
  "🖓": "thumbs-down",
  "🖔": "hand",
  "🖕": "hand",
  "🖖": "hand",
  "🖗": "hand",
  "🖘": "hand",
  "🖙": "hand",
  "🖚": "hand",
  "🖛": "hand",
  "🖜": "hand",
  "🖝": "hand",
  "🖞": "hand",
  "🖟": "hand",
  "🖠": "hand",
  "🖡": "hand",
  "🖢": "hand",
  "🖣": "hand",
  "🖤": "heart",
  "🖦": "keyboard",
  "🖧": "mouse",
  "🖨️": "printer",
  "🖩": "calculator",
  "🖪": "circle",
  "🖫": "circle",
  "🖬": "circle",
  "🖭": "circle",
  "🖮": "circle",
  "🖯": "circle",
  "🖰": "circle",
  "🖱️": "mouse",
  "🖲️": "circle",
  "🖳": "circle",
  "🖴": "circle",
  "🖵": "circle",
  "🖶": "circle",
  "🖷": "circle",
  "🖸": "circle",
  "🖹": "circle",
  "🖺": "circle",
  "🖻": "circle",
  "🖼️": "image",
  "🖽": "circle",
  "🖾": "circle",
  "🖿": "circle",
  "🗀": "folder",
  "🗁": "folder",
  "🗂️": "folder",
  "🗃️": "folder",
  "🗄️": "folder",
  "🗅": "folder",
  "🗆": "folder",
  "🗇": "folder",
  "🗈": "folder",
  "🗉": "folder",
  "🗊": "folder",
  "🗋": "folder",
  "🗌": "folder",
  "🗍": "folder",
  "🗎": "folder",
  "🗏": "folder",
  "🗐": "folder",
  "🗑️": "trash",
  "🗒": "file-text",
  "🗓": "calendar",
  "🗔": "circle",
  "🗕": "circle",
  "🗖": "circle",
  "🗗": "circle",
  "🗘": "circle",
  "🗙": "circle",
  "🗚": "circle",
  "🗛": "circle",
  "🗜": "circle",
  "🗝": "circle",
  "🗞": "newspaper",
  "🗟": "circle",
  "🗠": "circle",
  "🗡": "sword",
  "🗢": "circle",
  "🗣": "message-circle",
  "🗤": "circle",
  "🗥": "circle",
  "🗦": "circle",
  "🗧": "circle",
  "🗨": "message-circle",
  "🗩": "message-circle",
  "🗪": "message-circle",
  "🗫": "message-circle",
  "🗬": "message-circle",
  "🗭": "message-circle",
  "🗮": "message-circle",
  "🗯": "message-circle",
  "🗰": "message-circle",
  "🗱": "message-circle",
  "🗲": "message-circle",
  "🗳": "message-circle",
  "🗴": "message-circle",
  "🗵": "message-circle",
  "🗶": "message-circle",
  "🗷": "message-circle",
  "🗸": "message-circle",
  "🗹": "message-circle",
  "🗺": "map",
  "🗻": "mountain",
  "🗼": "tower",
  "🗽": "monument",
  "🗾": "map",
  "🗿": "monument",
} as const;

export type EmojiKey = keyof typeof EMOJI_TO_SVG_MAP;

/**
 * Configuración de tamaños para iconos
 */
export const ICON_SIZES = {
  sm: "w-4 h-4",
  md: "w-6 h-6",
  lg: "w-8 h-8",
  xl: "w-12 h-12",
} as const;

/**
 * Configuración de colores por variante
 */
export const ICON_VARIANTS = {
  default: "text-foreground",
  primary: "text-primary",
  secondary: "text-secondary",
  accent: "text-accent",
} as const;

/**
 * Obtiene el nombre del icono SVG correspondiente a un emoji
 */
export function getSvgIconName(emoji: string): string | null {
  return EMOJI_TO_SVG_MAP[emoji as EmojiKey] || null;
}

/**
 * Genera las clases CSS para un icono SVG
 */
export function getIconClasses(
  size: SvgIconProps["size"] = "md",
  variant: SvgIconProps["variant"] = "default",
): string {
  const sizeClass = ICON_SIZES[size];
  const variantClass = ICON_VARIANTS[variant];

  return `${sizeClass} ${variantClass}`;
}
