import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AnimationProvider } from "@/contexts/AnimationContext";
import { initWebVitals } from "@/lib/web-vitals";
import { DefaultBackground } from "@/components/ui/DefaultBackground";
import { FooterSection } from "@/components/landing/Footer.Section";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WebCode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Inicializar monitoreo de Web Vitals
  initWebVitals();

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Script necesario para prevenir el parpadeo del tema - contenido controlado y seguro */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme === 'dark' || theme === 'light') {
                    document.documentElement.classList.add(theme);
                    document.documentElement.style.colorScheme = theme;
                  } else {
                    var isDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                    var theme = isDark ? 'dark' : 'light';
                    document.documentElement.classList.add(theme);
                    document.documentElement.style.colorScheme = theme;
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AnimationProvider>
            <DefaultBackground />
            <div className="min-h-screen flex flex-col">
              <main className="flex-1">{children}</main>
              <FooterSection />
            </div>
          </AnimationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
